#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

############################## Public Cookbooks ###############################

cookbook 'apt',
  :git => 'https://github.com/opscode-cookbooks/apt.git', 
  #:ref => '1.5.0'
  :ref => 'master'

cookbook 'apache2',
  :git => 'https://github.com/opscode-cookbooks/apache2.git',
  #:ref => '1.2.0'
  :ref => 'master'

cookbook 'php',
  :git => 'https://github.com/opscode-cookbooks/php.git',
  #:ref => '1.1.0'
  :ref => 'master'

############################# Private Cookbooks ###############################

cookbook 'php_stack',
  :path => 'private-cookbooks/php_stack'

